<div style="background-color:#000047; padding:30px; border-radius:10px; color:white; text-align:center;">
    <img src='Figures/alinco_white_text.png' style="height:100px; margin-bottom:10px;"/>
    <h1>Módulo 2: Tareas Clásicas de NLP</h1>
    <h2>Clasificación de Texto Multiclase en NLP</h2>
</div>

## Clasificación de Texto

La **clasificación de texto** es la tarea de asignar automáticamente una o más categorías predefinidas a un fragmento de texto.

#### Tipos de clasificación

| Tipo | Descripción | Ejemplo |
|---|---|---|
| **Binaria** | 2 clases | Spam / No-spam, Positivo / Negativo |
| **Multi-clase** | N clases mutuamente excluyentes | Categoría de noticia |
| **Multi-etiqueta** | Múltiples clases posibles | Tags de un artículo |

#### Aplicaciones reales

```
📧 Filtro de spam           → Spam / Ham
😊 Análisis de sentimientos  → Positivo / Negativo / Neutro
📰 Categorización de noticias → Política / Deporte / Tecnología / ...
🔍 Detección de idioma       → Español / Inglés / Francés / ...
🚨 Detección de toxicidad    → Tóxico / No tóxico
⚖️ Clasificación legal       → Tipo de contrato / cláusula
```

### Pipeline general

```
Texto crudo
    ↓
Preprocesamiento (limpieza, tokenización, stopwords)
    ↓
Representación vectorial (BoW, TF-IDF, Embeddings)
    ↓
Modelo de clasificación (Naive Bayes, SVM, BERT...)
    ↓
Predicción + Evaluación
```

### Dataset Reseñas de Películas

Usaremos un conjunto de reseñas de películas etiquetadas como **positivas** (1) o **negativas** (0) para construir nuestro clasificador de sentimientos.

In [1]:
# Dataset de reseñas de películas (muestra representativa)
resenas = [
    # Positivas
    ("Esta película es absolutamente maravillosa, una obra maestra del cine.", 1),
    ("Increíble actuación, historia emocionante y efectos visuales impresionantes.", 1),
    ("Me encantó cada minuto, el director hizo un trabajo extraordinario.", 1),
    ("Una experiencia cinematográfica única, llena de emoción y belleza.", 1),
    ("Perfecta en todos los sentidos, la recomiendo ampliamente.", 1),
    ("El guion es brillante y los actores dan lo mejor de sí mismos.", 1),
    ("Simplemente espectacular, la mejor película del año sin duda.", 1),
    ("Emocionante de principio a fin, con giros inesperados magníficos.", 1),
    ("Una historia inspiradora contada de manera magistral.", 1),
    ("Gran película, entretenida y con un mensaje poderoso.", 1),
    ("Actuaciones sobresalientes y fotografía impecable.", 1),
    ("Un film que te deja pensando por días, brillantemente ejecutado.", 1),
    # Negativas
    ("Terrible película, una pérdida total de tiempo y dinero.", 0),
    ("Aburrida, predecible y con actuaciones pésimas.", 0),
    ("El peor filme que he visto en años, sin argumento ni emoción.", 0),
    ("Decepcionante y aburrida, no la recomiendo para nada.", 0),
    ("Historia sin sentido, personajes vacíos y final horrible.", 0),
    ("Mala actuación, pésimo guion y efectos especiales ridículos.", 0),
    ("Una completa decepción, esperaba mucho más de este director.", 0),
    ("Tediosa e insulsa, me quedé dormido a la mitad.", 0),
    ("Los diálogos son terribles y la trama no tiene coherencia alguna.", 0),
    ("Desperdicio de talento, película mediocre sin ningún valor.", 0),
    ("El argumento es ridículo y los efectos visuales son horribles.", 0),
    ("Nada funciona en esta película, es un fracaso absoluto.", 0),
]

textos  = [r for r, _ in resenas]
etiquetas = [e for _, e in resenas]

print(f"Total de reseñas: {len(resenas)}")
print(f"Positivas: {sum(etiquetas)}")
print(f"Negativas: {len(etiquetas) - sum(etiquetas)}")
print()
print("Ejemplos:")
for t, e in resenas[:3]:
    print(f"  [{'POS' if e==1 else 'NEG'}] {t}")

Total de reseñas: 24
Positivas: 12
Negativas: 12

Ejemplos:
  [POS] Esta película es absolutamente maravillosa, una obra maestra del cine.
  [POS] Increíble actuación, historia emocionante y efectos visuales impresionantes.
  [POS] Me encantó cada minuto, el director hizo un trabajo extraordinario.


## Análisis de Sentimientos con scikit-learn

### Multinomial Naive Bayes
Ahora usamos el pipeline de `scikit-learn` que combina **TF-IDF** + **Multinomial Naive Bayes** de forma eficiente.

- [Pipeline de sklearn](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html)

- [scikit-learn-pipelines guide](https://mahmoudyusof.github.io/blog/scikit-learn-pipelines)

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import numpy as np
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    textos, etiquetas, test_size=0.3, random_state=42, stratify=etiquetas
)


In [3]:
# Pipeline TF-IDF + Naive Bayes 
pipeline_nb = Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1,2), min_df = 1, max_features=5000, sublinear_tf = True)),
                         ('clf', MultinomialNB(alpha=0.5))
                       ])



In [4]:
X_train

['Desperdicio de talento, película mediocre sin ningún valor.',
 'Una experiencia cinematográfica única, llena de emoción y belleza.',
 'Mala actuación, pésimo guion y efectos especiales ridículos.',
 'Esta película es absolutamente maravillosa, una obra maestra del cine.',
 'Increíble actuación, historia emocionante y efectos visuales impresionantes.',
 'Nada funciona en esta película, es un fracaso absoluto.',
 'Aburrida, predecible y con actuaciones pésimas.',
 'Los diálogos son terribles y la trama no tiene coherencia alguna.',
 'Terrible película, una pérdida total de tiempo y dinero.',
 'El argumento es ridículo y los efectos visuales son horribles.',
 'Actuaciones sobresalientes y fotografía impecable.',
 'Perfecta en todos los sentidos, la recomiendo ampliamente.',
 'Simplemente espectacular, la mejor película del año sin duda.',
 'El peor filme que he visto en años, sin argumento ni emoción.',
 'Gran película, entretenida y con un mensaje poderoso.',
 'Una historia inspiradora

In [5]:
y_train

[0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1]

In [6]:
# Entrenar Naive Bayes con scikit-learn (TF-IDF) 
pipeline_nb.fit(X_train, y_train)

,steps,"[('tfidf', ...), ('clf', ...)]"
,transform_input,None
,memory,None
,verbose,False
,input,'content'
,encoding,'utf-8'
,decode_error,'strict'
,strip_accents,None
,lowercase,True
,preprocessor,None
,tokenizer,None


In [10]:
pipeline_nb.named_steps['tfidf'].get_feature_names_out()


array(['absolutamente', 'absolutamente maravillosa', 'absoluto',
       'aburrida', 'aburrida predecible', 'actuaciones',
       'actuaciones pésimas', 'actuaciones sobresalientes', 'actuación',
       'actuación historia', 'actuación pésimo', 'alguna', 'ampliamente',
       'argumento', 'argumento es', 'argumento ni', 'año', 'año sin',
       'años', 'años sin', 'belleza', 'cine', 'cinematográfica',
       'cinematográfica única', 'coherencia', 'coherencia alguna', 'con',
       'con actuaciones', 'con un', 'contada', 'contada de', 'de',
       'de emoción', 'de manera', 'de talento', 'de tiempo', 'del',
       'del año', 'del cine', 'desperdicio', 'desperdicio de', 'dinero',
       'diálogos', 'diálogos son', 'duda', 'efectos',
       'efectos especiales', 'efectos visuales', 'el', 'el argumento',
       'el peor', 'emocionante', 'emocionante efectos', 'emoción',
       'emoción belleza', 'en', 'en años', 'en esta', 'en todos',
       'entretenida', 'entretenida con', 'es', 'es absol

In [11]:
features_names = pipeline_nb.named_steps['tfidf'].get_feature_names_out()
coef_lambda = pipeline_nb.named_steps['clf'].feature_log_prob_ # probabilidad loglikelihood

In [13]:
coef_lambda[0]

array([-5.58043292, -5.58043292, -5.15958328, -5.05848   , -5.05848   ,
       -5.11241661, -5.05848   , -5.58043292, -5.17809985, -5.58043292,
       -5.13015389, -5.19397414, -5.58043292, -4.97538231, -5.15963517,
       -5.22175619, -5.58043292, -5.58043292, -5.22175619, -5.22175619,
       -5.58043292, -5.58043292, -5.58043292, -5.58043292, -5.19397414,
       -5.19397414, -5.11241661, -5.05848   , -5.58043292, -5.58043292,
       -5.58043292, -5.00755449, -5.58043292, -5.58043292, -5.14545024,
       -5.14405904, -5.58043292, -5.58043292, -5.58043292, -5.14545024,
       -5.14545024, -5.14405904, -5.19397414, -5.19397414, -5.58043292,
       -4.96476569, -5.13015389, -5.20500073, -4.97538231, -5.15963517,
       -5.22175619, -5.58043292, -5.58043292, -5.26145241, -5.58043292,
       -5.02428119, -5.22175619, -5.15958328, -5.58043292, -5.58043292,
       -5.58043292, -4.98410553, -5.58043292, -5.15963517, -5.15958328,
       -5.13015389, -5.13015389, -5.58043292, -5.58043292, -5.20

In [15]:
# Palabras más informativas por clase
top_neg = np.argsort(coef_lambda[0])[-10:][::-1]
top_neg

array([132, 167,  45,  48,  13,  61, 103,  31, 161,  55])

In [16]:
top_pos = np.argsort(coef_lambda[1])[-10:][::-1]
top_pos

array([189,  87, 132,  36,  97,  31, 165, 166,   7,  76])

In [19]:
#Top 10 palabras más NEGATIVAS
features_names[top_neg]

array(['película', 'son', 'efectos', 'el', 'argumento', 'es', 'los', 'de',
       'sin', 'en'], dtype=object)

In [20]:
#Top 10 palabras más POSITIVAS
features_names[top_pos]

array(['una', 'historia', 'película', 'del', 'la', 'de', 'sobresalientes',
       'sobresalientes fotografía', 'actuaciones sobresalientes',
       'fotografía impecable'], dtype=object)

In [ ]:
nueva_reseña = 'La pelicula estuvo muy aburrida'
# Tarea, como hacer una predicción apartir del pipeline que tenemos arriba


### Regresión Logística

La **Regresión Logística** aprende pesos para cada feature (palabra) usando la función sigmoide:

$$P(y=1 \mid x) = \sigma(w^T x + b) = \frac{1}{1 + e^{-(w^T x + b)}}$$


In [21]:
from sklearn.linear_model import LogisticRegression
#Pipeline con LogisticRegression
pipeline_lr = Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1,2), min_df = 1, max_features=5000, sublinear_tf = True)),
                        ('clr', LogisticRegression(C = 1.0, max_iter=1000, solver = 'lbfgs'))
    
]) 

In [22]:
#Entrenamoento LR
pipeline_lr.fit(X_train, y_train)

,steps,"[('tfidf', ...), ('clr', ...)]"
,transform_input,None
,memory,None
,verbose,False
,input,'content'
,encoding,'utf-8'
,decode_error,'strict'
,strip_accents,None
,lowercase,True
,preprocessor,None
,tokenizer,None


In [23]:
X_test

['Decepcionante y aburrida, no la recomiendo para nada.',
 'Emocionante de principio a fin, con giros inesperados magníficos.',
 'Me encantó cada minuto, el director hizo un trabajo extraordinario.',
 'Una completa decepción, esperaba mucho más de este director.',
 'Tediosa e insulsa, me quedé dormido a la mitad.',
 'Historia sin sentido, personajes vacíos y final horrible.',
 'El guion es brillante y los actores dan lo mejor de sí mismos.',
 'Un film que te deja pensando por días, brillantemente ejecutado.']

In [25]:
y_hat_test = pipeline_lr.predict(X_test) #predicción de las reseñas de testeo

In [28]:
# Coeficientes: importancia de cada feature
pipeline_lr.named_steps['clr'].coef_[0]

array([ 0.10183317,  0.10183317, -0.1100018 , -0.14241299, -0.14241299,
        0.01274661, -0.14241299,  0.15704956,  0.00572079,  0.12230729,
       -0.11573827, -0.09524272,  0.11102664, -0.16599945, -0.10477908,
       -0.08583346,  0.10316051,  0.10316051, -0.08583346, -0.08583346,
        0.10881004,  0.10183317,  0.10881004,  0.10881004, -0.09524272,
       -0.09524272, -0.01950668, -0.14241299,  0.12001402,  0.11526717,
        0.11526717, -0.00035802,  0.10881004,  0.11526717, -0.11090915,
       -0.11367359,  0.1785236 ,  0.10316051,  0.10183317, -0.11090915,
       -0.11090915, -0.11367359, -0.09524272, -0.09524272,  0.10316051,
       -0.07653089, -0.11573827,  0.01526486, -0.16599945, -0.10477908,
       -0.08583346,  0.12230729,  0.12230729,  0.0200097 ,  0.10881004,
       -0.06608772, -0.08583346, -0.1100018 ,  0.11102664,  0.12001402,
        0.12001402, -0.08801531,  0.10183317, -0.10477908, -0.1100018 ,
       -0.11573827, -0.11573827,  0.10316051,  0.10316051, -0.00

In [30]:
coeficientes_lr = pipeline_lr.named_steps['clr'].coef_[0]


In [31]:
#Top 10 indicadores de NEGATIVIDAD
np.argsort(coeficientes_lr)[:10]

array([167,  13,  48,   6,  27,   4, 143,   3, 144, 147])

In [32]:
#Top 10 indicadores de POSITIVIDAD
np.argsort(coeficientes_lr)[-10:]

array([198, 189, 166, 165,   7,  75,  91,  76,  36,  87])

In [33]:
features_names_lr = pipeline_lr.named_steps['tfidf'].get_feature_names_out()
features_names_lr

array(['absolutamente', 'absolutamente maravillosa', 'absoluto',
       'aburrida', 'aburrida predecible', 'actuaciones',
       'actuaciones pésimas', 'actuaciones sobresalientes', 'actuación',
       'actuación historia', 'actuación pésimo', 'alguna', 'ampliamente',
       'argumento', 'argumento es', 'argumento ni', 'año', 'año sin',
       'años', 'años sin', 'belleza', 'cine', 'cinematográfica',
       'cinematográfica única', 'coherencia', 'coherencia alguna', 'con',
       'con actuaciones', 'con un', 'contada', 'contada de', 'de',
       'de emoción', 'de manera', 'de talento', 'de tiempo', 'del',
       'del año', 'del cine', 'desperdicio', 'desperdicio de', 'dinero',
       'diálogos', 'diálogos son', 'duda', 'efectos',
       'efectos especiales', 'efectos visuales', 'el', 'el argumento',
       'el peor', 'emocionante', 'emocionante efectos', 'emoción',
       'emoción belleza', 'en', 'en años', 'en esta', 'en todos',
       'entretenida', 'entretenida con', 'es', 'es absol

In [34]:
features_names_lr[np.argsort(coeficientes_lr)[:10]] #Palabras mas negativas

array(['son', 'argumento', 'el', 'actuaciones pésimas', 'con actuaciones',
       'aburrida predecible', 'predecible', 'aburrida', 'predecible con',
       'pésimas'], dtype=object)

In [35]:
features_names_lr[np.argsort(coeficientes_lr)[-10:]] #Palabras mas positivas

array(['visuales impresionantes', 'una', 'sobresalientes fotografía',
       'sobresalientes', 'actuaciones sobresalientes', 'fotografía',
       'impecable', 'fotografía impecable', 'del', 'historia'],
      dtype=object)

In [36]:
print(classification_report(y_test, y_hat_test, target_names = ['Neg', 'Pos']))

              precision    recall  f1-score   support

         Neg       0.25      0.25      0.25         4
         Pos       0.25      0.25      0.25         4

    accuracy                           0.25         8
   macro avg       0.25      0.25      0.25         8
weighted avg       0.25      0.25      0.25         8



### Support Vector Machine (SVM)

Las **SVM** encuentran el **hiperplano de máximo margen** que separa las clases.

Para texto se usa típicamente un **kernel lineal** con TF-IDF, lo que resulta en uno de los clasificadores más potentes para NLP clásico.

$$\text{Clasificar: } f(x) = \text{sign}(w^T x + b)$$

**Ventajas:**
- Muy efectivo en espacios de alta dimensión (como TF-IDF)
- Robusto al overfitting
- El parámetro `C` controla el trade-off margen/errores

In [38]:
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV


In [40]:
#Pipeline
pipeline_svm = Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1,2), min_df = 1, max_features=5000, sublinear_tf = True)),
                        ('clsvm', CalibratedClassifierCV(LinearSVC(C = 1.0, max_iter = 2000)))
    
]) 

In [42]:
#Entrenamiento
pipeline_svm.fit(X_train, y_train)
# SVM Lineal 


,steps,"[('tfidf', ...), ('clsvm', ...)]"
,transform_input,None
,memory,None
,verbose,False
,input,'content'
,encoding,'utf-8'
,decode_error,'strict'
,strip_accents,None
,lowercase,True
,preprocessor,None
,tokenizer,None


In [45]:
y_pred_svm = pipeline_svm.predict(X_test)

In [46]:
y_pred_svm

array([1, 0, 1, 0, 0, 0, 1, 1])

In [47]:
print(classification_report(y_test, y_pred_svm, target_names = ['Neg', 'Pos']))

              precision    recall  f1-score   support

         Neg       0.75      0.75      0.75         4
         Pos       0.75      0.75      0.75         4

    accuracy                           0.75         8
   macro avg       0.75      0.75      0.75         8
weighted avg       0.75      0.75      0.75         8



In [48]:
# Probabilidades para reseñas nuevas
nuevas_resenas = [
    "Me aburrí muchísimo, una película terrible y sin sentido.",
    "Absolutamente fantástica, la mejor del año sin lugar a dudas.",
    "Algunos momentos buenos pero en general bastante mediocre.",
]


In [49]:
pipeline_svm.predict(nuevas_resenas)

array([1, 0, 1])

In [51]:
pipeline_svm.predict_proba([nuevas_resenas[0]])[0]

array([0.38834421, 0.61165579])

## Clasificación Multi-clase

Pasamos de binario (pos/neg) a **múltiples categorías**. Usaremos un dataset de noticias con 4 categorías.

In [52]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.preprocessing import LabelEncoder
from collections import Counter

# Subcategoría de 4 grupos temáticos
categorias = ['sci.space', 'rec.sport.baseball', 'talk.politics.guns', 'rec.autos']
news = fetch_20newsgroups(subset='all', categories=categorias,
                          remove=('headers', 'footers', 'quotes'))

print(f"Dataset: {len(news.data)} documentos, {len(news.target_names)} clases")
print(f"Clases: {news.target_names}")


Dataset: 3881 documentos, 4 clases
Clases: ['rec.autos', 'rec.sport.baseball', 'sci.space', 'talk.politics.guns']


In [55]:
news.target_names

['rec.autos', 'rec.sport.baseball', 'sci.space', 'talk.politics.guns']

In [57]:
# Distribución por clase
dist = Counter(news.target_names[t] for t in news.target)
print("\nDistribución:")
for clase, cnt in dist.most_common():
    print(f"  {clase}: {cnt}")



Distribución:
  rec.sport.baseball: 994
  rec.autos: 990
  sci.space: 987
  talk.politics.guns: 910


In [58]:
# División train test split
X_tr, X_te, y_tr, y_te = train_test_split(
    news.data, news.target, test_size=0.2, random_state=42, stratify=news.target)

In [61]:
# Comparar los 3 modelos en multi-clase
modelos = { 'Naive_Bayes': Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1,2), min_df = 1, max_features=5000, sublinear_tf = True)), ('clf', MultinomialNB(alpha=0.5))]),
            'Log_Reg': Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1,2), min_df = 1, max_features=5000, sublinear_tf = True)), ('clr', LogisticRegression(C=5, max_iter=1000))]),
            'svm': Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1,2), min_df = 1, max_features=5000, sublinear_tf = True)),('clsvm', CalibratedClassifierCV(LinearSVC(C = 1.0, max_iter = 2000)))])
}

In [63]:
resultados = {}
for mod, pipeline_mod in modelos.items():
    pipeline_mod.fit(X_tr, y_tr)
    y_p_test = pipeline_mod.predict(X_te)
    acc = accuracy_score(y_te, y_p_test)
    resultados[mod]  = acc
    print(f'\n ====== {mod}, accuracy: {acc} ==================')
    print(classification_report(y_te, y_p_test, target_names =news.target_names))
    


 ====== Naive_Bayes, accuracy: 0.8674388674388674 ==================
                    precision    recall  f1-score   support

         rec.autos       0.83      0.84      0.84       198
rec.sport.baseball       0.83      0.91      0.87       199
         sci.space       0.93      0.84      0.88       198
talk.politics.guns       0.89      0.87      0.88       182

          accuracy                           0.87       777
         macro avg       0.87      0.87      0.87       777
      weighted avg       0.87      0.87      0.87       777


 ====== Log_Reg, accuracy: 0.8584298584298584 ==================
                    precision    recall  f1-score   support

         rec.autos       0.78      0.89      0.83       198
rec.sport.baseball       0.88      0.85      0.87       199
         sci.space       0.88      0.85      0.86       198
talk.politics.guns       0.93      0.84      0.88       182

          accuracy                           0.86       777
         macro avg 

#### Métricas de Evaluación

| Métrica | Fórmula | Cuándo usar |
|---|---|---|
| **Accuracy** | $\frac{TP+TN}{TP+TN+FP+FN}$ | Clases balanceadas |
| **Precision** | $\frac{TP}{TP+FP}$ | Cuando los FP son costosos |
| **Recall** | $\frac{TP}{TP+FN}$ | Cuando los FN son costosos |
| **F1-Score** | $\frac{2 \cdot P \cdot R}{P+R}$ | Balance precision/recall |
| **AUC-ROC** | Área bajo curva ROC | Evaluación global del clasificador |

In [64]:
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
from sklearn.metrics import ConfusionMatrixDisplay, roc_curve, auc
from sklearn.preprocessing import label_binarize

#  Comparación de modelos 
print("   Resumen Comparativo   ")
print(f"{'Modelo':<15} {'Accuracy':>10}")
print("-" * 28)
for nombre, acc in sorted(resultados.items(), key=lambda x: -x[1]):
    bar = '||' * int(acc * 30)
    print(f"{nombre:<15} {acc:>8.3f}  {bar}")

   Resumen Comparativo   
Modelo            Accuracy
----------------------------
Naive_Bayes        0.867  ||||||||||||||||||||||||||||||||||||||||||||||||||||
svm                0.864  ||||||||||||||||||||||||||||||||||||||||||||||||||
Log_Reg            0.858  ||||||||||||||||||||||||||||||||||||||||||||||||||


## 10. Predicción con Texto Libre

Ejemplo de uso del mejor modelo para clasificar noticias nuevas.

In [66]:
# Usar el mejor modelo (?) para predicciones nuevas
mejor_modelo = modelos['Naive_Bayes']

noticias_nuevas = [
    "NASA announced a new mission to explore the surface of Mars next year.",
    "The Yankees won the World Series with an extraordinary pitching performance.",
    "New legislation on firearm regulations passed in the Senate today.",
    "The new electric sports car reaches 0 to 60 mph in just 2.5 seconds.",
]
for noticia in noticias_nuevas:
    pred_idx = mejor_modelo.predict([noticia])[0]
    pred_clase = news.target_names[pred_idx]
    probs = mejor_modelo.predict_proba([noticia])[0]

    print(f'Noticia: {noticia}...')
    print(f'Clase: {pred_clase}')
    print(f'Propb: {max(probs)}')

Noticia: NASA announced a new mission to explore the surface of Mars next year....
Clase: sci.space
Propb: 0.8467595945856096
Noticia: The Yankees won the World Series with an extraordinary pitching performance....
Clase: rec.sport.baseball
Propb: 0.9406447441982594
Noticia: New legislation on firearm regulations passed in the Senate today....
Clase: talk.politics.guns
Propb: 0.6789078047315769
Noticia: The new electric sports car reaches 0 to 60 mph in just 2.5 seconds....
Clase: rec.autos
Propb: 0.8714000199337399


In [ ]:
#Clasificación de noticias nuevas 
